name: Build SNES ROM

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git

      - name: Clone PVSnesLib
        run: |
          git clone https://github.com/alekmaul/pvsneslib.git

      - name: Build tools
        run: |
          cd pvsneslib/tools
          make

      - name: Locate compiler
        run: |
          find pvsneslib -name "816-tcc"

      - name: Build ROM
        run: |
          COMPILER=$(find pvsneslib -name 816-tcc | head -n 1)

          $COMPILER \
          -Ipvsneslib/include \
          -O2 \
          -o fukka.elf \
          main.c \
          -Lpvsneslib/lib \
          -lpvsneslib

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: fukka-rom
          path: "*.elf"
