name: Build SNES ROM

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git

      - name: Clone PVSnesLib
        run: |
          git clone https://github.com/alekmaul/pvsneslib.git
          echo "PVSNESLIB_HOME=$GITHUB_WORKSPACE/pvsneslib" >> $GITHUB_ENV

      - name: Build SNES tools
        run: |
          cd pvsneslib/tools
          make

      - name: Build ROM
        run: |
          export PVSNESLIB_HOME=$GITHUB_WORKSPACE/pvsneslib

          $PVSNESLIB_HOME/tools/816-opt/816-tcc \
          -I$PVSNESLIB_HOME/include \
          -O2 \
          -o fukka.elf \
          main.c \
          -L$PVSNESLIB_HOME/lib \
          -lpvsneslib

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: fukka-rom
          path: "*.elf"
