name: Build SNES ROM

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Install PVSnesLib
      run: |
        sudo apt update
        sudo apt install -y build-essential git python3

        git clone https://github.com/alekmaul/pvsneslib.git

        echo "PVSNESLIB_HOME=$PWD/pvsneslib" >> $GITHUB_ENV
        echo "$PWD/pvsneslib/devkitsnes/bin" >> $GITHUB_PATH

    - name: Build Game
      run: |
        export PVSNESLIB_HOME=$PWD/pvsneslib
        make

    - name: Upload ROM
      uses: actions/upload-artifact@v4
      with:
        name: fukka-rom
        path: "*.sfc"
